---
title: "Final Project"
author: "Matthew Turk - 604625958"
date: "5/30/2020"
output: html_document
---

```{r}
library(readr)
library(dplyr)
dryer <- read_tsv("hair_dryer.tsv")
microwave <- read_tsv("microwave.tsv")
pacifier <- read_tsv("pacifier.tsv")
```

```{r}
library(dplyr)
dryer <- mutate(dryer, help_score = ifelse(total_votes==0, 0, helpful_votes^2/total_votes))
```

```{r}
library(dplyr)
date_list <- strsplit(dryer$review_date, split = '/')
day <- numeric()
month <- numeric()
year <- numeric()
for (entry in date_list) {
  day <- c(day, as.numeric(entry[2]))
  month <- c(month, as.numeric(entry[1]))
  year <- c(year, as.numeric(entry[3]))
}
dryer <- mutate(dryer, day = day)
dryer <- mutate(dryer, month = month)
dryer <- mutate(dryer, year = year)

```

```{r}
days_since_release <- numeric()
for (i in seq_len(nrow(dryer))) {
  years <- dryer$year[i] - 2002
  months <- dryer$month[i] - 3
  if (months < 0) {
    years <- years - 1
    months <- months + 12
  }
  days_since_release[i] <- round(years*365.25 + months*30.4375)
}
dryer <- mutate(dryer, days_since_release = days_since_release)
```

```{r}
not_helpful <- which(dryer$help_score == 0)
length(not_helpful)
helpful <- which(dryer$help_score > 5)
helpful_headline <- dryer$review_headline[helpful]
helpful_reviews <- dryer$review_body[helpful]
length(helpful_reviews)
helpful_ratings <- dryer$star_rating[helpful]

more_helpful <- which(dryer$help_score > 100) # 30 reviews
more_helpful_headline <- dryer$review_headline[more_helpful]
more_helpful_reviews <- dryer$review_body[more_helpful]
more_helpful_ratings <- dryer$star_rating[more_helpful]
```
```{r}
more_helpful_reviews

```


```{r}
words <- list()
for (i in 1:30) {
  words[i] <- strsplit(more_helpful_reviews[i], " ")
}
words
```


```{r}
library(stringr)
one_star <- which(more_helpful_ratings == 1)
not <- which(str_detect(one_star_review, "not"))

#best <- which(str_detect(more_helpful_reviews, "best"))
#more_helpful_ratings
#more_helpful_reviews[best]

```

```{r}
library(stringr)
helpful_one_star <- which(dryer$star_rating == 1 | dryer$star_rating == 2)
length(helpful_one_star)
helpful_one_star_review <- dryer$review_body[helpful_one_star]
broke <- which(str_detect(helpful_one_star_review, "broke"))   # 6/75
#helpful_one_star_review[broke]

bad <- which(str_detect(helpful_one_star_review, "bad"))     # 8/75
#helpful_one_star_review[bad]

cheap <- which(str_detect(helpful_one_star_review, "cheap"))       # 5/75
#helpful_one_star_review[cheap]

expensive <- which(str_detect(helpful_one_star_review, "expensive"))   # 5/75
#helpful_one_star_review[expensive]

money <- which(str_detect(helpful_one_star_review, "money")) # 13/75
#helpful_one_star_review[money]

not <- which(str_detect(helpful_one_star_review, "not"))     # 52/75
#helpful_one_star_review[not]

burn <- which(str_detect(helpful_one_star_review, "burn"))    # 20/75
#helpful_one_star_review[burn]

work <- which(str_detect(helpful_one_star_review, "work"))    # 21/75
#helpful_one_star_review[work]

poor <- which(str_detect(helpful_one_star_review, "poor"))    # 2/75
#helpful_one_star_review[poor]

voltage <- which(str_detect(helpful_one_star_review, "loud")) # 4/75
#helpful_one_star_review[voltage]

mo <- which(str_detect(helpful_one_star_review, "month"))     # 24/75
#helpful_one_star_review[mo]

days <- which(str_detect(helpful_one_star_review, "week"))
#helpful_one_star_review[days]

hot <- which(str_detect(helpful_one_star_review, "hot"))    # 24/75
#helpful_one_star_review[hot]

wet <- which(str_detect(helpful_one_star_review, "wet"))    # 3/75
#helpful_one_star_review[wet]

shut <- which(str_detect(helpful_one_star_review, "shut"))
#helpful_one_star_review[shut]

H <- c(length(not), length(work), length(mo), length(hot), length(money), length(burn), length(days), length(broke), length(bad))
M <- c("not", "month", "work", "hot", "burn", "week", "money", "bad", "broke")
barplot(H, names.arg = M , xlab = "Keywords", ylab = "Frequency", main = "Keywords in 1671 One/Two Star Rating Reviews", las = 2, horiz = TRUE)


```

```{r}
one_star_rating <- which(dryer$star_rating == 1)
num_1star <- length(one_star_rating)
one_star_review <- dryer$review_body[one_star_rating]

two_star_rating <- which(dryer$star_rating == 2)
num_2star <- length(two_star_rating)

three_star_rating <- which(dryer$star_rating == 3)
num_3star <- length(three_star_rating)

four_star_rating <- which(dryer$star_rating == 4)
num_4star <- length(four_star_rating)

five_star_rating <- which(dryer$star_rating == 5)
num_5star <- length(five_star_rating)

L <- c(num_1star, num_2star, num_3star, num_4star, num_5star)
N <- c("1", "2", "3", "4", "5")
barplot(L, names.arg = N, main = "Distribution of ratings for hair dryer")
```

```{r}
h_one_star <- which(dryer$star_rating == 1 & dryer$help_score > 10)
num_h1 <- length(h_one_star)

h_two_star <- which(dryer$star_rating == 2 & dryer$help_score > 10)
num_h2 <- length(h_two_star)

h_three_star <- which(dryer$star_rating == 3 & dryer$help_score > 10)
num_h3 <- length(h_three_star)

h_four_star <- which(dryer$star_rating == 4 & dryer$help_score > 10)
num_h4 <- length(h_four_star)

h_five_star <- which(dryer$star_rating == 5 & dryer$help_score > 10)
num_h5 <- length(h_five_star)

hehe <- c(num_h1, num_h2, num_h3, num_h4, num_h5)
barplot(hehe, names.arg = N, main = "Distribution of ratings with helpfulness score > 10 for hair dryer")
```

```{r}
most_consecutive_val = function(x, val = 1) {
  with(rle(x), max(lengths[values == val]))
}

#apply(dryer[-1], MARGIN = 1, most_consecutive_val)
```

```{r}
dryer_products <- unique(dryer$product_id)
dryer_products[1]
#dryer_products

count <- vector(length = length(dryer_products))
j <- 1
while (j < length(dryer_products)) {
  i <- 1
  while (i < length(dryer$product_id)) {
    id <- dryer$product_id[i]
    if (id == dryer_products[j]) {
      count[j] = count[j] + 1
    }
    i = i + 1
  }
  j = j + 1
}
#count = count / length(dryer$product_id)
count

#matter_count <- which(count >= 100)
#matter_count

#x <- which(dryer$product_id == dryer_products[matter_count])
#analyze the products that have over 100 reviews

#b003_ratings <- dryer$star_rating[which(dryer$product_id == "B003V264WW")]
#hist(b003_ratings)
```
```{r}
helpful_count <- which(count >= 300)
dryer_products[helpful_count]
```

```{r}
dryer1_index <- which(dryer$product_id == dryer_products[helpful_count][1])
reviews_dryer1 <- dryer$review_body[dryer1_index]
#reviews_dryer1
reviews_dryer1_StarRating <- with(dryer, tapply(dryer$star_rating[dryer1_index], dryer$review_body[dryer1_index], mean))
#reviews_dryer1_Star
```
#replicate for all 5 dryers with more than 300 reviews
```{r}
dryer2_index <- which(dryer$product_id == dryer_products[helpful_count][2])
reviews_dryer2 <- dryer$review_body[dryer2_index]
reviews_dryer2_StarRating <- with(dryer, tapply(dryer$star_rating[dryer2_index], dryer$review_body[dryer2_index], mean))

dryer3_index <- which(dryer$product_id == dryer_products[helpful_count][3])
reviews_dryer3 <- dryer$review_body[dryer3_index]
reviews_dryer3_StarRating <- with(dryer, tapply(dryer$star_rating[dryer3_index], dryer$review_body[dryer3_index], mean))

dryer4_index <- which(dryer$product_id == dryer_products[helpful_count][4])
reviews_dryer4 <- dryer$review_body[dryer4_index]
reviews_dryer4_StarRating <- with(dryer, tapply(dryer$star_rating[dryer4_index], dryer$review_body[dryer4_index], mean))

dryer5_index <- which(dryer$product_id == dryer_products[helpful_count][5])
reviews_dryer5 <- dryer$review_body[dryer5_index]
reviews_dryer5_StarRating <- with(dryer, tapply(dryer$star_rating[dryer5_index], dryer$review_body[dryer5_index], mean))

```
# perform str_detect on these functions
```{r}
dryer1_1star_index <- which(dryer$star_rating[dryer1_index] == 1)     # disappointed, too heavy, broke easily
dryer1_1star <- reviews_dryer1[dryer1_1star_index]
#dryer1_1star

dryer2_1star_index <- which(dryer$star_rating[dryer2_index] == 1)     # not hot enough
dryer2_1star <- reviews_dryer2[dryer2_1star_index]
#dryer2_1star

dryer3_1star_index <- which(dryer$star_rating[dryer3_index] == 1)     # has retractable cord that broke
dryer3_1star <- reviews_dryer3[dryer3_1star_index]
#dryer1_1star

dryer4_1star_index <- which(dryer$star_rating[dryer4_index] == 1)     # no durability
dryer4_1star <- reviews_dryer4[dryer4_1star_index]
#dryer1_1star

dryer5_1star_index <- which(dryer$star_rating[dryer5_index] == 1)     # has a retractable cord that broke, not hot enough
dryer5_1star <- reviews_dryer5[dryer5_1star_index]
#dryer1_1star

bad_1 <- which(str_detect(dryer1_1star, "spark"))
cat(length(bad_1), length(dryer1_1star), " ")        # 21/36 said it shot sparks or died, 23 had problem w time

bad_2 <- which(str_detect(dryer2_1star, "not"))
cat(length(bad_2), length(dryer2_1star), " ")        # 6/17 had problems with heat, 4 attachments, 9 time

bad_3 <- which(str_detect(dryer3_1star, "plug"))
cat(length(bad_3), length(dryer3_1star), " ")        # 30/41 time, 11/41 had outlet prob

bad_4 <- which(str_detect(dryer4_1star, "cheap"))      
cat(length(bad_4), length(dryer4_1star), " ")        # 20/32 time, 10 cheap

bad_5 <- which(str_detect(dryer5_1star, "cord"))
cat(length(bad_5), length(dryer5_1star), " ")        # 5/10 broken, 5/10 cord

reviews_dryer1[dryer1_1star_index]
#reviews_dryer2[dryer2_1star_index]
#reviews_dryer3[dryer3_1star_index]
#reviews_dryer4[dryer4_1star_index]
#reviews_dryer5[dryer5_1star_index]
```
#finds common keywords specific to the star rating
```{r}
slices <- c(21+6+11+5, 23+9+30+20, 4+5, 10)
lbls <- c("broken", "not durable", "bad attachments", "poor quality")
color <- c("red", "blue", "yellow", "green")
pie(slices, labels = lbls, col = color, main = "What One-Star Reviewers did NOT like about their dryer", angle = 45, density = 50)
```

```{r}
dryer1_5star_index <- which(dryer$star_rating[dryer1_index] == 5)     # disappointed, too heavy, broke easily
dryer1_5star <- reviews_dryer1[dryer1_5star_index]
#dryer1_1star

dryer2_5star_index <- which(dryer$star_rating[dryer2_index] == 5)     # not hot enough
dryer2_5star <- reviews_dryer2[dryer2_5star_index]
#dryer2_1star

dryer3_5star_index <- which(dryer$star_rating[dryer3_index] == 5)     # has retractable cord that broke
dryer3_5star <- reviews_dryer3[dryer3_5star_index]
#dryer11star

dryer4_5star_index <- which(dryer$star_rating[dryer4_index] == 5)     # no durability
dryer4_5star <- reviews_dryer4[dryer4_5star_index]
#dryer1_1star

dryer5_5star_index <- which(dryer$star_rating[dryer5_index] == 5)     # has a retractable cord that broke, not hot enough
dryer5_5star <- reviews_dryer5[dryer5_5star_index]
#dryer1_1star

good_1 <- which(str_detect(dryer1_5star, "prof"))
cat(length(good_1), length(dryer1_5star), " ")        # 165/355 time (quick, speed, fast), 45/355 money (price), 55/355 power, 22/355 temp, 52/355 quiet, 48/355 professional qualilty

good_2 <- which(str_detect(dryer2_5star, "quality"))
cat(length(good_2), length(dryer2_5star), " ")        # 90/323 time, 45 money, 52 power, 14 temp, 37 quiet, 28 quality

good_3 <- which(str_detect(dryer3_5star, "temp"))
cat(length(good_3), length(dryer3_5star), " ")        # 62/331 time, 44 money, 54 power, 5 temp, 11 quiet, 5 quality

good_4 <- which(str_detect(dryer4_5star, "temp"))      
cat(length(good_4), length(dryer4_5star), " ")        # 58/229 time, 52 money, 17 power, 8 temp, 16 quiet, 13 qual

good_5 <- which(str_detect(dryer5_5star, "temp"))
cat(length(good_5), length(dryer5_5star), " ")        # 51/174 time, 27 money, 20 power, 13 temp, 24 quiet, 15 qual

#reviews_dryer1[dryer1_5star_index]
#reviews_dryer2[dryer2_5star_index]
#reviews_dryer3[dryer3_5star_index]
#reviews_dryer4[dryer4_5star_index]
#reviews_dryer5[dryer5_5star_index]
```

```{r}
slices <- c(165+90+62+58+51, 45+45+44+52+27, 55+52+54+17+20, 22+14+5+8+13, 52+37+11+16+24, 48+28+5+13+15)
lbls <- c("quick dry", "reasonable price", "high power", "good temperature", "quiet", "professional quality")
color <- c("red", "blue", "yellow", "green", "purple", "magenta")
pie(slices, labels = lbls, col = color, main = "What Five-Star Reviewers liked about their dryer", angle = 45, density = 50)
```

```{r}
ratings_by_product <- with(dryer, tapply(dryer$star_rating,dryer$product_id,mean))
#ratings_by_product
success <- count * (ratings_by_product)
finder <- which(success >= 1000)
finder
success[finder]
hist(success, main = "Histogram of Adjusted Success Score for Hair Dryer", xlab = "Success Score")
#hist(success)
hist(ratings_by_product, main = "Average Ratings by Product", xlab = "average ratings for hair dryer products")
#reviews_by_product <- with(dryer, tapply(nrow(dryer), dryer$product_id))
# make various histograms of diff success scores, as well as big picture
# B00006IV46
```

```{r}
success_over_time <- vector()

for (i in 2002:2015) {
  for (j in 1:12) {
    if (dryer$product_id == )
  }
}
```

```{r}
counter <- 0
history <- c()
for (i in (nrow(dryer)-1):1) {
  if (dryer$star_rating[i] == dryer$star_rating[i+1]) {
    counter <- counter + 1
  } else {counter <- 0}
  history <- c(history, counter)
}
plot(history, type = 'l', main = "Finding Consecutive Ratings over Time")
```

```{r}
index <- which(history > 8)
hist(dryer$star_rating[nrow(dryer)-index-1], main = "Histogram of Star Ratings after 8 Consecutive Ratings", xlab = "Star Ratings")

```

